### ISSUE TITLE
Unable to specify files for spell checking

### ISSUE THREAD

**Issue by M1troll** [hcodes/yaspeller#191]
# Problem
I tried to add a yaspeller hook to my project to check the documentation (`.md` and `.rst` files).
I specified `fileExtensions`:
```json
"fileExtensions": [
      ".md",
      ".rst"
    ],
```
but `yaspeller` still checks other files as well (.yaml, .py and etc.)

I also try to exclude this files in `excludeFiles`
```json
"excludeFiles": [
        "*.py",
        "*.yaml",
        ".py",
        ".yaml"
    ]
```
but even this had no effect.

**Note:** specifying the full path to the file works, but do I really need to add the paths of all the files of my project here? It looks wrong.

# Reproduce
You can clone my test repo for reproduce my situation: https://github.com/M1troll/speller

And follow steps below:
1. Install `pre-commit`:
```bash
pip install pre-commit
```
2. Add hook in `.pre-commit-config.yaml`:
```yaml
repos:
  - repo: https://github.com/hcodes/yaspeller.git
    rev: v8.0.1
    hooks:
      - id: yaspeller
```
3. Run pre-commit:
```bash
pre-commit run --hook-stage push --all-files  
```
